export { getFirstMatchDay } from "./getFirstMatchDay";
export { getMatchings } from "./getMatchings";
export { nameToUrlName } from "./nameToUrlName";
export { saveNewLeague } from "./saveNewLeague";
export { shuffle } from "./shuffle";
export * from "./truncateString";
export * from "./addDatesToMatchings";
export * from "./setMessage";
export { useWindowDimensions } from "./useWindowDimensions";
export { validateNewLeague } from "./validateNewLeague";
